apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: webserver
 labels:
  type: webserver
  author: Mayank
spec:
 replicas: 3
 selector:
  matchLabels:
   type: webserver
 template:
  metadata:
   name: webserver
   labels:
    type: webserver
  spec:
   containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
         name: http
