apiVersion: v1
kind: ReplicationController
metadata:
 name: httpd-rc
 labels:
  author: Mayank
spec:
 replicas: 2
 template:
  metadata:
   name: httpd-pod
   labels:
    author: Mayank
  spec:
   containers:
    - name: myhttpd
      image: nginx
      ports:
       - containerPort: 80
         name: http
