apiVersion: v1
kind: Service
metadata:
 name: nginx-service
 labels:
  author: Mayank
spec:
 type: NodePort
 ports:
  - targetPort: 80
    port: 80
 type: LoadBalancer
 selector:
  author: Mayank
  type: reverse-proxy
